DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE EMPLEADOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DNI VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL);